baseurl: "https://tomodutch.com"
defaultContentLanguage: ja-jp
languages:
  ja-JP:
    contentDir: content/ja
    languageCode: "ja-JP"
    giscusLang: "ja"
    LanguageName: 日本語 (Japanese)
    title: "友ダッチ"
    params:
      dateFormat: ":date_long"
    menu:
      header:
        - name: 記事
          url: "/articles/"
      footer:
        - name: RSS
          url: "/index.xml"
  en-US:
    contentDir: content/en
    languageCode: "en-US"
    giscusLang: "en"
    LanguageName: 英語 (English)
    title: "友ダッチ"
    params:
      dateFormat: ":date_long"
    menu:
      header:
        - name: Articles
          url: "/en-us/articles/"
      footer:
        - name: RSS
          url: "/index.xml"
    weight: 1

theme: "hugo-tania"
paginate: 6


disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: ""
  siteDesc: ""
  dateFormat: ":date_full"
  author: "Thomas"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email:
    facebook:
    github: https://github.com/tomodutch
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: tomodutch/tomodutch
      id: R_kgDOHU0a4g
      mapping: "url"
      category:
        name: Announcements
        id: DIC_kwDOHU0a4s4CPFbC

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
